name: build

concurrency:
  group: build-${{ github.head_ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
    tags-ignore:
      - llvmorg-*
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        include:
          - name: MacOS 10.15
            host_runner: macos-10.15
            darwin_version: darwin_19
          - name: MacOS 11
            host_runner: macos-11
            darwin_version: darwin_20
          - name: MacOS 12
            host_runner: macos-12
            darwin_version: darwin_21
    name: Build llvm on ${{ matrix.name }}
    runs-on: ${{ matrix.host_runner }}
    steps:
    - name: Install dependency
      run: |
        brew install ninja boost cmake

    - name: Build llvm
      run: |
        git clone https://github.com/llvm/llvm-project.git --branch=llvmorg-14.0.6 --depth=1
        cmake -Bbuild -GNinja -DCMAKE_BUILD_TYPE=Release -DCPACK_GENERATOR=ZIP -DLLVM_TARGETS_TO_BUILD="X86" -DLLVM_ENABLE_PROJECTS="lld;clang;clang-tools-extra" llvm-project/llvm
        cmake --build build

    - name: Package llvm
      run: |
        cmake --build build --target package

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: llvm-14.0.6-${{ matrix.darwin_version }}
        path: build/LLVM-14.0.6-Darwin.zip
        retention-days: 5
