name: build

concurrency:
  group: build-${{ github.head_ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
    tags-ignore:
      - llvmorg-*
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build llvm on MacOS
    runs-on: macos-12
    steps:
    - name: Install dependency
      run: |
        brew install cmake ninja

    - name: Get LLVM source code
      run: |
        git clone --branch llvmorg-14.0.5 --depth 1 https://github.com/llvm/llvm-project.git
    - name: Build LLVM
      run: |
        cmake -Bbuild -GNinja -DCMAKE_BUILD_TYPE=Release -DCPACK_GENERATOR=ZIP -DLLVM_TARGETS_TO_BUILD="X86" -DLLVM_ENABLE_PROJECTS="lld;clang;clang-tools-extra" llvm-project/llvm
        cmake --build build

    - name: Package llvm
      run: |
        cmake --build build --target package

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: llvm
        path: build/*.zip
        retention-days: 5
